# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1387, 891)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(120, 10, 791, 471))
        self.image.setText("")
        self.image.setObjectName("image")
        self.camera = QtWidgets.QPushButton(self.centralwidget)
        self.camera.setGeometry(QtCore.QRect(20, 70, 93, 28))
        self.camera.setObjectName("camera")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(400, 590, 101, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.OgrNo = QtWidgets.QLabel(self.layoutWidget)
        self.OgrNo.setObjectName("OgrNo")
        self.verticalLayout_4.addWidget(self.OgrNo)
        self.Sinif = QtWidgets.QLabel(self.layoutWidget)
        self.Sinif.setObjectName("Sinif")
        self.verticalLayout_4.addWidget(self.Sinif)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(530, 590, 171, 141))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ogrNoEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.ogrNoEdit.setObjectName("ogrNoEdit")
        self.verticalLayout_3.addWidget(self.ogrNoEdit)
        self.sinifComboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.sinifComboBox.setObjectName("sinifComboBox")
        self.verticalLayout_3.addWidget(self.sinifComboBox)
        self.takephoto = QtWidgets.QPushButton(self.centralwidget)
        self.takephoto.setGeometry(QtCore.QRect(0, 110, 121, 41))
        self.takephoto.setObjectName("takephoto")
        self.yuz = QtWidgets.QLabel(self.centralwidget)
        self.yuz.setGeometry(QtCore.QRect(920, 30, 431, 411))
        self.yuz.setText("")
        self.yuz.setObjectName("yuz")
        self.Kaydet = QtWidgets.QPushButton(self.centralwidget)
        self.Kaydet.setGeometry(QtCore.QRect(800, 620, 151, 41))
        self.Kaydet.setObjectName("Kaydet")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 590, 111, 191))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Ad = QtWidgets.QLabel(self.layoutWidget1)
        self.Ad.setObjectName("Ad")
        self.verticalLayout.addWidget(self.Ad)
        self.Soyad = QtWidgets.QLabel(self.layoutWidget1)
        self.Soyad.setObjectName("Soyad")
        self.verticalLayout.addWidget(self.Soyad)
        self.dogumTarihi = QtWidgets.QLabel(self.layoutWidget1)
        self.dogumTarihi.setObjectName("dogumTarihi")
        self.verticalLayout.addWidget(self.dogumTarihi)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(150, 590, 201, 201))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.adEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.adEdit.setObjectName("adEdit")
        self.verticalLayout_2.addWidget(self.adEdit)
        self.soyadEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.soyadEdit.setObjectName("soyadEdit")
        self.verticalLayout_2.addWidget(self.soyadEdit)
        self.dgmtrhEdit = QtWidgets.QDateEdit(self.layoutWidget2)
        self.dgmtrhEdit.setObjectName("dgmtrhEdit")
        self.verticalLayout_2.addWidget(self.dgmtrhEdit)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(980, 550, 521, 181))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1387, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.camera.setText(_translate("MainWindow", "kamera "))
        self.OgrNo.setText(_translate("MainWindow", "Öğrenci No :"))
        self.Sinif.setText(_translate("MainWindow", "Sınıf :"))
        self.takephoto.setText(_translate("MainWindow", "resim çek"))
        self.Kaydet.setText(_translate("MainWindow", "kaydet"))
        self.Ad.setText(_translate("MainWindow", "Ad :"))
        self.Soyad.setText(_translate("MainWindow", "Soyad :"))
        self.dogumTarihi.setText(_translate("MainWindow", "Doğum Tarihi :"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">BİLGİLENDİRME </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#4800ff;\">RESİM ÇEKMEDEN ÖNCE LÜTFEN BİLGİLERİNİZİ EKSİKSİZ VE DOĞRU BİÇİMDE GİRİNİZ. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#4800ff;\">ARDINDAN RESİM ÇEKMEK İÇİN kamera BUTONUNA BASINIZ. KAMERA AÇILACAKTIR. KAMERA AÇILDIKTAN SONRA resim çek BUTONUNA BASARAK YÜZÜNÜZ TAM GÖRÜNECEK ŞEKİLDE RESMİ ÇEKİN.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#4800ff;\">EĞER ÇEKTİĞİNİZ RESMİ BEĞENMEZSENİZ resmi tekrar çek BUTONUNA BASARAK BİR ÖNCEKİ ÇEKTİĞİNİZ RESMİ SİLEBİLİRSİNİZ. ARDINDAN TEKRAR kamera BUTONUNA BASARAK YENİDEN RESİM ÇEKME ADIMLARINI UYGULAYINIZ. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#4800ff;\">SON OLARAK KAYDET BUTONUNA BASMAYI UNUTMAYINIZ!!! </span></p></body></html>"))
